In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/master_dataset.csv")

In [3]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 956500 entries, 0 to 956499
Data columns (total 23 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            956500 non-null  str
 1   item_id       956500 non-null  str
 2   dept_id       956500 non-null  str
 3   cat_id        956500 non-null  str
 4   store_id      956500 non-null  str
 5   state_id      956500 non-null  str
 6   d             956500 non-null  str
 7   sales         956500 non-null  int64
 8   date          956500 non-null  str
 9   wm_yr_wk      956500 non-null  int64
 10  weekday       956500 non-null  str
 11  wday          956500 non-null  int64
 12  month         956500 non-null  int64
 13  year          956500 non-null  int64
 14  event_name_1  956500 non-null  str
 15  event_type_1  956500 non-null  str
 16  event_name_2  956500 non-null  str
 17  event_type_2  956500 non-null  str
 18  snap_CA       956500 non-null  int64
 19  snap_TX       956500 non-null  int64
 20  snap_WI       956500 non-null  int64
 21  day           956500 non-null  int64
 22  sell_price    776516 non-null  float64
dtypes: float64(1), int64(9), str(13)
memory usage: 167.8 MB

In [4]:
df["date"] = pd.to_datetime(df["date"])

In [5]:
df = df.sort_values(["item_id", "store_id", "date"])

In [6]:
df["lag_1"] = df.groupby(["item_id", "store_id"])["sales"].shift(1)

In [7]:
df["lag_7"] = df.groupby(["item_id", "store_id"])["sales"].shift(7)

In [8]:
df["rolling_mean_7"] = (
    df.groupby(["item_id", "store_id"])["sales"]
      .transform(lambda x: x.rolling(7).mean())
)

In [9]:
df["rolling_std_7"] = (
    df.groupby(["item_id", "store_id"])["sales"]
      .transform(lambda x: x.rolling(7).std())
)

In [10]:
df[
    [
        "sales",
        "lag_1",
        "lag_7",
        "rolling_mean_7",
        "rolling_std_7",
    ]
].head(15)

      sales  lag_1  lag_7  rolling_mean_7  rolling_std_7
0         0    NaN    NaN             NaN            NaN
500       0    0.0    NaN             NaN            NaN
1000      0    0.0    NaN             NaN            NaN
1500      0    0.0    NaN             NaN            NaN
2000      0    0.0    NaN             NaN            NaN
2500      0    0.0    NaN             NaN            NaN
3000      0    0.0    NaN             0.0            0.0
3500      0    0.0    0.0             0.0            0.0
4000      0    0.0    0.0             0.0            0.0
4500      0    0.0    0.0             0.0            0.0
5000      0    0.0    0.0             0.0            0.0
5500      0    0.0    0.0             0.0            0.0
6000      0    0.0    0.0             0.0            0.0
6500      0    0.0    0.0             0.0            0.0
7000      0    0.0    0.0             0.0            0.0

In [11]:
df.fillna(0, inplace=True)

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,event_type_2,snap_CA,snap_TX,snap_WI,day,sell_price,lag_1,lag_7,rolling_mean_7,rolling_std_7
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,No Event,0,0,0,29,0.00,0.0,0.0,0.0,0.0
500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0,2011-01-30,11101,...,No Event,0,0,0,30,0.00,0.0,0.0,0.0,0.0
1000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0,2011-01-31,11101,...,No Event,0,0,0,31,0.00,0.0,0.0,0.0,0.0
1500,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0,2011-02-01,11101,...,No Event,1,1,0,1,0.00,0.0,0.0,0.0,0.0
2000,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0,2011-02-02,11101,...,No Event,1,0,1,2,0.00,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954499,HOBBIES_2_084_CA_1_validation,HOBBIES_2_084,HOBBIES_2,HOBBIES,CA_1,CA,d_1909,0,2016-04-20,11612,...,No Event,0,0,0,20,5.97,0.0,1.0,0.0,0.0
954999,HOBBIES_2_084_CA_1_validation,HOBBIES_2_084,HOBBIES_2,HOBBIES,CA_1,CA,d_1910,0,2016-04-21,11612,...,No Event,0,0,0,21,5.97,0.0,0.0,0.0,0.0
955499,HOBBIES_2_084_CA_1_validation,HOBBIES_2_084,HOBBIES_2,HOBBIES,CA_1,CA,d_1911,0,2016-04-22,11612,...,No Event,0,0,0,22,5.97,0.0,0.0,0.0,0.0
955999,HOBBIES_2_084_CA_1_validation,HOBBIES_2_084,HOBBIES_2,HOBBIES,CA_1,CA,d_1912,0,2016-04-23,11613,...,No Event,0,0,0,23,5.97,0.0,0.0,0.0,0.0
956499,HOBBIES_2_084_CA_1_validation,HOBBIES_2_084,HOBBIES_2,HOBBIES,CA_1,CA,d_1913,0,2016-04-24,11613,...,No Event,0,0,0,24,5.97,0.0,0.0,0.0,0.0

In [12]:
df.to_csv(
    "../data/processed/master_dataset_features.csv",
    index=False
)